---
- name: Deploy RHEL8 VM
  hosts: 127.0.0.1
  connection: local
  gather_facts: false
  vars_files:
    - ../vaults/template.yml
  vars:
    ansible_python_interpreter: '{{ ansible_playbook_python }}'

  tasks:
  - ansible.builtin.include_tasks:
      file: provision_vm.yml
    loop: "{{ vm_info }}"


- name: Deploy RHEL8 VM
  hosts: rhel_guest
  gather_facts: false
  vars_files:
    - ../vaults/template.yml
  tasks:
  - name: Wait for host to be up
    ansible.builtin.wait_for_connection:

  - name: Gather facts
    ansible.builtin.gather_facts:


  # Ugly.  Please fix. :)
  - name: Download Satellite Registration script
    ansible.builtin.uri:
      url: "https://satellite1.mgmt.toal.ca/register?\
        hostgroup_id=9&location_id=2&operatingsystem_id=12&organization_id=1&\
        setup_insights=false&setup_remote_execution=true&\
        update_packages=false"
      headers:
        Authorization: 'Bearer {{ vault_satellite_bearer_token }}'
      dest: ./sat_reg.sh
      mode: 0700
      validate_certs: false

  - name: Execute Registration Script
    command:
      cmd: ./sat_reg.sh
    ignore_errors: true
...
