---
- name: Create the VM
  community.vmware.vmware_guest:
    datacenter: 'SagelyDC'
    folder: /vm/Demo
    resource_pool: Demo
    name: '{{ item.name }}'
    state: poweredon
    guest_id: rhel8_64Guest
    annotation: "Test"
    disk:
      - size_gb: 20
        type: thin
        datastore: 'EVO2TB'
    networks:
      - name: DPG-Sandbox
        dvswitch_name: DSwitch001
        ip: '{{ item.ip }}'
        netmask: 255.255.240.0
        gateway: 192.168.16.1
        dns_servers:
          - 192.168.16.1
        start_connected: true
        connected: true
        type: static
    hardware:
      memory_mb: '{{ item.vm_memory }}'
      num_cpus: 2
    customization:
      dns_servers:
        - 192.168.16.1
      domain: demo.toal.ca
      hostname: '{{ item.name }}'
    template: 'rhel81-x64-v1'
    wait_for_ip_address: false
  delegate_to: localhost
  throttle: 1
  register: new_vm_info

- name: Set tags
  community.vmware.vmware_tag_manager:
    object_type: VirtualMachine
    object_name: '{{ item.name }}'
    tag_names:
      - '{{ item.app_name }}'
    state: add

- name: Add Host to Inventory
  ansible.builtin.add_host:
    name: '{{ item.name }}'
    group: 'rhel_guest'
    ansible_host: '{{ item.ip }}'